core/urls.py
from django.urls import path
from .views import (
    remove_from_cart,
    reduce_quantity_item,
    add_to_cart,
    Home,
    OrderSummaryView,
    CheckoutView
)
from django.conf import settings
from django.conf.urls.static import static






app_name = 'core'

urlpatterns = [
    path('order-summary', OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
    path('reduce-quantity-item/<pk>/', reduce_quantity_item, name='reduce-quantity-item'),
   # path('checkout', CheckoutView.as_view(), name='checkout'),
    
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kitchen/urls.py
from django.contrib import admin
from django.urls import path, include 
from core.views import Product,CheckoutView,Signup
from core.views import (
    remove_from_cart,
    reduce_quantity_item,
    add_to_cart,
    Home,
    OrderSummaryView,
    CheckoutView
)
from django.contrib.auth import views as auth_views

from django.views.static import serve
from django.conf.urls import url
from django.conf import settings

from django.views.generic import RedirectView
from django.conf.urls import url

urlpatterns = [
    path('', include('core.urls', namespace='core')), 
    path('', Home, name='home'),
    path('admin/', admin.site.urls),
    path('login', auth_views.LoginView.as_view(template_name='registration/login.html'), name="login"),
    path('logout', auth_views.LogoutView.as_view(template_name='home.html'), name="logout"),
    path('product/<int:pk>/', Product, name='product'),
    path('PaymentView/<int:pk>/', Product, name='product'),
  # path('Checkout/<int:pk>/', CheckoutView, name='checkout'),
    path('checkout', CheckoutView, name='checkout'),
    path('signup', Signup, name='signup'),
    url(r'^favicon\.ico$',RedirectView.as_view(url='/static/images/favicon.ico')),

    path('order-summary', OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
    path('reduce-quantity-item/<pk>/', reduce_quantity_item, name='reduce-quantity-item'),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
   

]

# path('accounts/', include('django.contrib.auth.urls')),

core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.contrib.auth import get_user_model


import cloudinary
from cloudinary.models import CloudinaryField




CATEGORY = (
    ('H', 'Electronics'),
    ('S', 'Cleaning and supplies'),
    ('O', 'Storage Supplies'),
    ('C', 'Cuttleries'),
    ('B', 'Bathroom'),
    ('E', 'Beddings'),
    ('G', 'Gas'),
)

LABEL = (
    ('N', 'New'),
    ('BS', 'Best Seller')
)

class Item(models.Model):
    item_name = models.CharField(max_length=100)
    image = CloudinaryField('image')
    #image=cloudinary.models.CloudinaryField('image')
    #image = models.ImageField(upload_to="products/")
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY, max_length=20)
    label = models.CharField(choices=LABEL, max_length=2)
    description = models.TextField()

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            "pk" : self.pk
        
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            "pk" : self.pk
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            "pk" : self.pk
        })










class ProductImage(models.Model):
    item_name = models.CharField(max_length=100)
    
    item = models.ForeignKey(Item, on_delete=models.CASCADE)  
    image = models.ImageField(upload_to="products/images/")

    def __str__ (self):
        return self.item_name

class CheckoutAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100,null=True)
  

  

    def __str__(self):
        return self.user.username


class Sales(models.Model):
    customer_name = models.CharField(max_length=50)
    number = models.CharField(max_length=10)
    location = models.CharField(max_length=20)
    
 

    def __str__ (self):
        return self.customer_name
    
        
    

class OrderItem(models.Model):
    #user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.item_name}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_discount_item_price()
        return self.get_total_item_price()
    
    

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    checkout_address = models.ForeignKey(
        'CheckoutAddress', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username
    
    def get_total_price(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total




class Payment(models.Model):
    stripe_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, 
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

templates/base.html
{% load static %}

{% load cart_template_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>kitchen-sale</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href=" {% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body{
      background-color: rgb(160, 144, 144);
    },
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }



    
.navbar {
  overflow: hidden;
  background-color: rgba(116, 55, 124, 0.993);
}

.navbar a {
  float: left;
  font-size: 16px;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 16px;  
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.navbar a:hover, .dropdown:hover .dropbtn {
  background-color: rgb(168, 153, 153);
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: rgb(160, 29, 29);
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {
  background-color: #ddd;
}

.dropdown:hover .dropdown-content {
  display: block;
}

  </style>


    {% block extra_head %}
    {% endblock extra_head %}

</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/" style="color: cornsilk;">
        <strong class="blue-text">Doorstep</strong>
      </a>

          
         <div class="apa" style="text-align: left;">
            {% if user.is_authenticated %}
            
             <!-- <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
                {% if request.user|cart_item_count != 0 %}
                  <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                {% endif %}
                <i class="fas fa-shopping-cart"></i>
                <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                </a>-->
            
            
                 <a class="nav-link waves-effect" style="color: cornsilk;"><strong>
                Hi {{ user.username }}! <i class="fas fa-id-card"></i></strong>
                </a>
            
             
                
            
            {% else %}
               
                <a class="nav-link waves-effect" href="{% url 'signup' %}"> Sign-Up &nbsp<i class="fas fa-sign-in-alt"></i></a>
               
                </div>
            {% endif %}
        
          </div>
      </div>

    </div>
  </nav>
  <!-- Navbar -->
  <div class="mt-5 pt-4">
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}}" role="alert">
            {{ message }}
        </div>
      {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% include "footer.html" %}


    {% include "script.html" %}

    {% block extra_script %}
    {% endblock extra_script %}

</body>

</html>

templates/checkout.html
{% extends 'base.html' %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}

{% block content %}

<main >
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form method="POST" class="card-body">
            {% csrf_token %}
            <h3 style="border: 0px; border-radius: 15px; text-align: center;">{{ user.username }}   </h3> 
              <!--address-->
              <div class="md-form mb-5" >
                <label for="address" class="">Reciever Name :</label>
                <br>
                {{form.customer_name}}
                
                
               
              </div>

              <!--address-2-->
              <div class="md-form mb-5" >
                <label for="address-2" class="">Your Location :</label><br>
                {{ form.location }}
               
              </div>

              <!--Grid row-->
              <div class="row">

               

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="zip">Phone Number :</label><br>
                  <div class='phone' >{{ form.number }}</div>
                  <div class="invalid-feedback">
                    Phone Number required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr>

              <div class="custom-control custom-checkbox">
                <input {% if form.same_billing_address.value %}checked{% endif %} type="checkbox" class="custom-control-input" name="same_billing_address" id="same-address">
                <label class="custom-control-label" for="same-address">Location address is the same as my point of pickup</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input {% if form.save_info.value %}checked{% endif %} type="checkbox" class="custom-control-input" name="save_info" id="save-info">
                <label class="custom-control-label" for="save-info">Save this information for next time</label>
              </div>

              <hr>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>
             
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Confirm Purchase</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>

          <!-- Cart -->

          {% for p in pd %}
          <ul class="list-group mb-3 z-depth-1">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Product name</h6>
                <br><span class="text-muted">{{ p.item_name }}</span>
              </div>
              

            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Product Price</h6>
                <br> <span class="text-muted">{{ p.price }}</span>
              </div>
             

            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
             
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (Ksh)</span>
              <strong>{{ p.price }}</strong>
            </li>
          </ul>
          {% endfor %}
          <!-- Cart -->

          <!-- Promo code -->
          

       
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/footer.html
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn" style="background-color: rgba(116, 55, 124, 0.993);">

<br>
  <div class="fota" style="color: cyan;">
  {% if user.is_authenticated %}
    

    <a class="nav-link waves-effect" href="{% url 'logout' %}" style="color: rgb(226, 227, 235);"><strong>Log-Out <i class="fas fa-users"></i></strong></a>
    {% else %}

    <a class="nav-link waves-effect" href="{% url 'signup' %}"> Sign-Up &nbsp<i class="fas fa-sign-in-alt"></i></a>
    {% endif %}
  </h4>
   
  <!--/.Call to action-->

  <hr class="my-4">

  <!-- Socials -->
 <h3> Contact us:</h3>
 

  <a href="tel:0720616098" onclick="ga('send', 'event', { eventCategory: 'Contact', eventAction: 'Call', eventLabel: 'Mobile Button'});"><p class="call-button"  class="btn btn-primary btn-md my-0 p" style="color: white;" ><i class="fas fa-phone-alt"></i>  Call Us:&nbsp: 0720616098</p>
  </a>

 <p style="color: white;"><i class="fas fa-sms"></i> &nbsp SMS : 0720616098</p>

  <div class="pb-4">
    <h2>   <a href="https://www.instagram.com/doorstep_254/" target="_blank" style="color: white;">
      <i class="fab fa-facebook" ></i>
    </a>
    &nbsp | &nbsp
    <a href="https://www.instagram.com/doorstep_254" target="_blank" style="color: white">
      <i class="fab fa-instagram"></i></i></i>
    </a></h2>

      <!--
    <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
      <i class="fab fa-youtube mr-3"></i>
    </a>

    <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
      <i class="fab fa-google-plus-g mr-3"></i>
    </a>

    <a href="https://dribbble.com/mdbootstrap" target="_blank">
      <i class="fab fa-dribbble mr-3"></i>
    </a>

    <a href="https://pinterest.com/mdbootstrap" target="_blank">
      <i class="fab fa-pinterest mr-3"></i>
    </a>

    <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
      <i class="fab fa-github mr-3"></i>
    </a>

    <a href="http://codepen.io/mdbootstrap/" target="_blank">
      <i class="fab fa-codepen mr-3"></i>
    </a>
  </div>-->
  <!-- Social icons -->

  <br><br>
  <p>Doorstep is a shop located in Ruiru,Kihunguro.<br>
    Mainly focused on selling quality products,
    providing quality customer service,<br>
    without forgeting the affoirdable prices.<br>
    <strong>Shop With Us</strong> 
    <br>and share the experience.
  </p>
  <br><br>
  <h5 style="color: black;"><i class="fa fa-copyright" aria-hidden="true"> Copyright P. Karanja 2021</i></h5>

  

</footer>

templates/footer_BACKUP_1075.html
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn" style="background-color: rgba(116, 55, 124, 0.993);">

<br>
  <div class="fota" style="color: cyan;">
  {% if user.is_authenticated %}
    

    <a class="nav-link waves-effect" href="{% url 'logout' %}" style="color: rgb(226, 227, 235);"><strong>Log-Out <i class="fas fa-users"></i></strong></a>
    {% else %}

    <a class="nav-link waves-effect" href="{% url 'signup' %}"> Sign-Up &nbsp<i class="fas fa-sign-in-alt"></i></a>
    {% endif %}
  </h4>
   
  <!--/.Call to action-->

  <hr class="my-4">

  <!-- Socials -->
 <h3> Contact us:</h3>
 

  <a href="tel:0720616098" onclick="ga('send', 'event', { eventCategory: 'Contact', eventAction: 'Call', eventLabel: 'Mobile Button'});"><p class="call-button"  class="btn btn-primary btn-md my-0 p" style="color: white;" ><i class="fas fa-phone-alt"></i>  Call Us:&nbsp: 0720616098</p>
  </a>

 <p style="color: white;"><i class="fas fa-sms"></i> &nbsp SMS : 0720616098</p>

  <div class="pb-4">
    <h2>   <a href="https://www.instagram.com/doorstep_254/" target="_blank" style="color: white;">
      <i class="fab fa-facebook" ></i>
    </a>
    &nbsp | &nbsp
<<<<<<< HEAD
    <a href="https://www.instagram.com/doorstep_254/" target="_blank" style="color: white">
=======
    <a href="https://www.instagram.com/doorstep_254" target="_blank" style="color: white">
>>>>>>> 553243abbf640d12e59341b3eaf7023a0ca655f8
      <i class="fab fa-instagram"></i></i></i>
    </a></h2>

      <!--
    <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
      <i class="fab fa-youtube mr-3"></i>
    </a>

    <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
      <i class="fab fa-google-plus-g mr-3"></i>
    </a>

    <a href="https://dribbble.com/mdbootstrap" target="_blank">
      <i class="fab fa-dribbble mr-3"></i>
    </a>

    <a href="https://pinterest.com/mdbootstrap" target="_blank">
      <i class="fab fa-pinterest mr-3"></i>
    </a>

    <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
      <i class="fab fa-github mr-3"></i>
    </a>

    <a href="http://codepen.io/mdbootstrap/" target="_blank">
      <i class="fab fa-codepen mr-3"></i>
    </a>
  </div>-->
  <!-- Social icons -->

  <br><br>
  <p>Doorstep is a shop located in Ruiru,Kihunguro.<br>
    Mainly focused on selling quality products,
    providing quality customer service,<br>
    without forgeting the affoirdable prices.<br>
    <strong>Shop With Us</strong> 
    <br>and share the experience.
  </p>
  <br><br>
  <h5 style="color: black;"><i class="fa fa-copyright" aria-hidden="true"> Copyright P. Karanja 2021</i></h5>

  

</footer>

templates/logout.html
{% block content %}
  <h1>Logout Page</h1>
{% endblock %}

templates/order_summary.html
{% extends 'base.html' %}

{% block content %}

<main>
    <div class= "container">
        <div class="table-responsive text-nowrap">
    <h3>
        <strong>Your Cart</strong>
    </h3>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item Name</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.item_name }}</td>
            <td>
            {% if order_item.item.discount_price %}
                <del>${{ order_item.item.price}}</del> 
                ${{ order_item.item.discount_price }}
            {% else %}
                ${{ order_item.item.price}}
            {% endif %}

            </td>
            <td>
                <a href="{% url 'core:reduce-quantity-item' order_item.item.pk %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.pk %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ${{ order_item.get_discount_item_price }} 
                <span class="badge badge-success" >Saved ${{ order_item.get_amount_saved }}</span>
            {% else %}
                ${{ order_item.get_total_item_price}}
            {% endif %}
             <a href="{% url 'core:remove-from-cart' order_item.item.pk %}">
                <i class="fas fa-trash float-right text-danger"></i>
             </a>

            </td>
        </tr>

        {% empty %}
        <tr>
            <td colspan="5">Your Cart Empty</td>
        </tr>

         <tr>
            <td colspan="5">
                <a href="/" class="btn btn-primary float-right">Continue Shopping</a>
            </td>
        </tr>

        {% endfor %}

        {% if object.get_total_price %}
        <tr>
            <td colspan="4"><b>Total Order Price</b></td>
            <td>${{ object.get_total_price }}</td>
        </tr>
         <tr>
            <td colspan="5">
                <a href="{% url 'core:checkout' %}" class="btn btn-warning float-right ml-2">Checkout</a>
                <a href="/" class="btn btn-primary float-right">Continue Shopping</a>
            </td>
        </tr>
        
        {% endif %}
        
        </tbody>
    </table>

        </div>
    </div>
</main>

{% endblock content %}

templates/product.html
{% extends 'base.html' %}

{% block content %}

<!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      {% for p in pd %}
      <!--Grid row-->
      <div class="row wow fadeIn">
      
        <!--Grid column-->
        <div class="col-md-6 mb-4">
          <p class="lead font-weight-bold">{{ p.item_name }}</p>

          <img src="{{ p.image.url }}" class="img-fluid" alt="" style="width: 850px; height: 500px;"
          >

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">{{ object.get_label_display }}</span>
              </a>
            </div>

            <p class="lead">

            <span class="mr-1">
              <strong>Price: {{ p.price }}</strong>
            </span><br>
            <span>Discount Price: {{ p.discount_price }}</span>

            <!-- {% if object.discount_price %}
              <span class="mr-1">
              <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
            {% else %}
             <span>${{ object.price }}</span>
            {% endif %} -->

            </p>

            

            <p> Description: <br>{{ p.description }}</p>

            
            <!--{% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <!--
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}

            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p" >Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
            </a>

            {{ object.get_quantity_in_chart }}
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p" >Remove From cart
                <i class="fas fa-trash ml-1"></i>
            </a>
           
          -->
            <!--Card image-->

            {% if user.is_authenticated %}


            <!--
              <a href="{% url 'checkout'  %}" class="grey-text">
              
            <button class="btn btn-primary btn-lg btn-block">Continue to checkout</button>
              -->

              <a href="tel:0720616098" onclick="ga('send', 'event', { eventCategory: 'Contact', eventAction: 'Call', eventLabel: 'Mobile Button'});"><p class="call-button"  class="btn btn-primary btn-md my-0 p" 
                style="border:5px solid rgba(116, 55, 124, 0.993); text-align: center; margin: 22px; border-radius: 12px; background-color:rgb(66, 202, 32) ; color: #000;"
                >Call To Order &nbsp<i class="fas fa-phone"></i></p></a>


          
            </a>

            {% else %}


            <!--
            <a class="nav-link waves-effect" href="{% url 'signup' %}"> Sign-Up &nbsp<i class="fas fa-sign-in-alt"></i></a>
            -->
            

            
            <a href="{% url 'signup' %}" class="btn btn-primary btn-md my-0 p" >
              Sign-Up &nbsp
              <i class="fas fa-sign-in-alt"></i>
          </a>
            


          </div>
           {% endif %}

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Kitchen space</h4>

       
      <!--Grid row-->
    {% endfor %}
    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/script.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
// Animations initialization
new WOW().init();

</script>